from __future__ import annotations

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import httpx

from db.client import get_db

APP_BASE_URL = os.environ.get("FRONTEND_BASE_URL", "http://localhost:3000")
TEST_EMAIL_FALLBACK = os.environ.get("TEST_EMAIL_FALLBACK", "")
DEFAULT_SENDER_EMAIL = os.environ.get(
    "SENDER_EMAIL", "recruitx Marketplace <notifications@recruitx.ai>"
)


def get_profile_email(profile_id: str) -> str:
    """Helper to retrieve real email from calendar_connections or fall back to developer's verified email."""
    db = get_db()
    try:
        res = (
            db.table("calendar_connections")
            .select("email")
            .eq("profile_id", profile_id)
            .execute()
        )
        if res.data and res.data[0].get("email"):
            email = res.data[0]["email"]
            # If it's a mock email generated by the system, we route it to the verified email for testing
            if "recruitx-scheduler.ai" in email:
                return TEST_EMAIL_FALLBACK or email
            return email
    except Exception as e:
        print(f"[get_profile_email error] {str(e)}")
    return TEST_EMAIL_FALLBACK


async def send_email_notification(to_email: str, subject: str, html_body: str):
    """Sends an email notification using Gmail SMTP (if configured), Resend (fallback), or stdout logging."""
    if not to_email:
        return False

    smtp_user = os.environ.get("SMTP_USER")
    smtp_pass = os.environ.get("SMTP_PASSWORD")

    if smtp_user and smtp_pass:
        try:
            # Construct standard MIME email
            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"] = os.environ.get(
                "SENDER_EMAIL", f"recruitx Marketplace <{smtp_user}>"
            )
            msg["To"] = to_email

            # Attach HTML content
            msg.attach(MIMEText(html_body, "html"))

            # Send securely via Gmail SMTP (Port 587 with TLS)
            server = smtplib.SMTP("smtp.gmail.com", 587)
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, to_email, msg.as_string())
            server.quit()

            print(
                f"[Email Send Success via Gmail SMTP] To: {to_email}, Subject: {subject}"
            )
            return True
        except Exception as e:
            print(f"[Email Send Exception via Gmail SMTP] {str(e)}")

    resend_api_key = os.environ.get("RESEND_API_KEY")
    if resend_api_key:
        try:
            async with httpx.AsyncClient() as client:
                res = await client.post(
                    "https://api.resend.com/emails",
                    headers={
                        "Authorization": f"Bearer {resend_api_key}",
                        "Content-Type": "application/json",
                    },
                    json={
                        "from": DEFAULT_SENDER_EMAIL,
                        "to": to_email,
                        "subject": subject,
                        "html": html_body,
                    },
                )
                if res.status_code < 300:
                    print(
                        f"[Email Send Success via Resend] To: {to_email}, Subject: {subject}"
                    )
                    return True
                else:
                    print(
                        f"[Email Send Error via Resend] {res.status_code}: {res.text}"
                    )
        except Exception as e:
            print(f"[Email Send Exception via Resend] {str(e)}")

    # Beautiful Ascii Console Fallback
    border = "=" * 80
    print(border)
    print(f"📧 [MOCK EMAIL SENT] TO: {to_email}")
    print(f"📧 SUBJECT: {subject}")
    print(border)
    # Simple HTML-to-Text layout for logging readability
    text_content = (
        html_body.replace("<br/>", "\n")
        .replace("<p>", "")
        .replace("</p>", "\n")
        .replace("<strong>", "")
        .replace("</strong>", "")
    )
    print(text_content.strip())
    print(border)
    return True


async def notify_new_match(negotiation_id: str):
    """Notifies both candidate and recruiter that a matching negotiation has been started."""
    db = get_db()
    try:
        # Fetch negotiation details including nested profile emails
        neg_res = (
            db.table("negotiations")
            .select(
                "id, fit_score, candidate_notes, candidate:candidates(id, title, profile_id), recruiter:recruiters(id, position, company, profile_id)"
            )
            .eq("id", negotiation_id)
            .execute()
        )

        if not neg_res.data:
            return

        neg = neg_res.data[0]
        cand = neg.get("candidate")
        rec = neg.get("recruiter")

        if not cand or not rec:
            return

        # Dynamically override recruiter details if a job_id is associated in candidate_notes
        notes = neg.get("candidate_notes") or ""
        import re

        match = re.search(r"([a-f0-9\-]{36})", notes)
        if match:
            job_id = match.group(1)
            job_res = db.table("jobs").select("*").eq("id", job_id).execute()
            if job_res.data:
                job = job_res.data[0]
                rec = dict(rec)
                rec["position"] = job.get("title") or rec.get("position")
                rec["company"] = job.get("company") or rec.get("company")

        # Get Candidate profile name
        cand_prof = (
            db.table("profiles").select("name").eq("id", cand["profile_id"]).execute()
        )
        # Get Recruiter profile name
        rec_prof = (
            db.table("profiles").select("name").eq("id", rec["profile_id"]).execute()
        )

        c_email = get_profile_email(cand["profile_id"])
        c_name = cand_prof.data[0].get("name") if cand_prof.data else "Candidate"

        r_email = get_profile_email(rec["profile_id"])
        r_name = rec_prof.data[0].get("name") if rec_prof.data else "Recruiter"

        # Notify Candidate
        if c_email:
            subject = f"🤖 Agent Active: New Match Found for {rec.get('position')} at {rec.get('company')}!"
            body = (
                f"<p>Hello {c_name},</p>"
                f"<p>Our matching engine detected a high-fit match (<strong>Fit Score: {int(neg.get('fit_score', 0))}%</strong>) "
                f"for the <strong>{rec.get('position')}</strong> role at <strong>{rec.get('company')}</strong>.</p>"
                f"<p>Your Candidate Agent is initiating negotiations right now. You can watch the chat or step in at any time here:</p>"
                f"<p><a href='{APP_BASE_URL}/negotiations/{negotiation_id}'>View Active Negotiation Room</a></p>"
                f"<p>Best regards,<br/>recruitx Autonomous Agent</p>"
            )
            await send_email_notification(c_email, subject, body)

        # Notify Recruiter
        if r_email:
            subject = f"🤖 Agent Active: New Applicant Match for {rec.get('position')}!"
            body = (
                f"<p>Hello {r_name},</p>"
                f"<p>We found a qualified candidate for your <strong>{rec.get('position')}</strong> position "
                f"(<strong>Fit Score: {int(neg.get('fit_score', 0))}%</strong>).</p>"
                f"<p>Your Recruiter Agent has begun screening requirements and discussing salary expectations in the negotiation room:</p>"
                f"<p><a href='{APP_BASE_URL}/negotiations/{negotiation_id}'>View Active Negotiation Room</a></p>"
                f"<p>Best regards,<br/>recruitx Autonomous Agent</p>"
            )
            await send_email_notification(r_email, subject, body)

    except Exception as e:
        print(f"[notify_new_match error] {str(e)}")


async def notify_takeover_paused(negotiation_id: str, paused_by_role: str):
    """Notifies the opposing party that a human has taken over the negotiation."""
    db = get_db()
    try:
        neg_res = (
            db.table("negotiations")
            .select(
                "id, candidate:candidates(profile_id), recruiter:recruiters(profile_id)"
            )
            .eq("id", negotiation_id)
            .execute()
        )

        if not neg_res.data:
            return

        neg = neg_res.data[0]
        cand = neg.get("candidate")
        rec = neg.get("recruiter")

        if not cand or not rec:
            return

        # If paused by recruiter, notify candidate. If paused by candidate, notify recruiter.
        target_profile_id = (
            cand["profile_id"] if paused_by_role == "recruiter" else rec["profile_id"]
        )

        prof_res = (
            db.table("profiles").select("name").eq("id", target_profile_id).execute()
        )
        if not prof_res.data:
            return

        email = get_profile_email(target_profile_id)
        name = prof_res.data[0].get("name") or "User"

        opposing_label = "Recruiter" if paused_by_role == "recruiter" else "Candidate"

        if email:
            subject = (
                f"⚠️ Human Takeover: The {opposing_label} has stepped into the room"
            )
            body = (
                f"<p>Hello {name},</p>"
                f"<p>The human <strong>{opposing_label}</strong> has paused their AI agent and taken over the conversation manually in the negotiation room.</p>"
                f"<p>Go to the room to chat with them directly:</p>"
                f"<p><a href='{APP_BASE_URL}/negotiations/{negotiation_id}'>Open Chat Room</a></p>"
                f"<p>Best regards,<br/>recruitx Notification Service</p>"
            )
            await send_email_notification(email, subject, body)
    except Exception as e:
        print(f"[notify_takeover_paused error] {str(e)}")


async def notify_meeting_booked(negotiation_id: str, meeting_time: str, meet_link: str):
    """Notifies both parties that a meeting has been booked and includes Google Meet details."""
    db = get_db()
    try:
        neg_res = (
            db.table("negotiations")
            .select(
                "id, candidate_notes, candidate:candidates(profile_id), recruiter:recruiters(position, company, profile_id)"
            )
            .eq("id", negotiation_id)
            .execute()
        )

        if not neg_res.data:
            return

        neg = neg_res.data[0]
        cand = neg.get("candidate")
        rec = neg.get("recruiter")

        if not cand or not rec:
            return

        # Dynamically override recruiter details if a job_id is associated in candidate_notes
        notes = neg.get("candidate_notes") or ""
        import re

        match = re.search(r"([a-f0-9\-]{36})", notes)
        if match:
            job_id = match.group(1)
            job_res = db.table("jobs").select("*").eq("id", job_id).execute()
            if job_res.data:
                job = job_res.data[0]
                rec = dict(rec)
                rec["position"] = job.get("title") or rec.get("position")
                rec["company"] = job.get("company") or rec.get("company")

        cand_prof = (
            db.table("profiles").select("name").eq("id", cand["profile_id"]).execute()
        )
        rec_prof = (
            db.table("profiles").select("name").eq("id", rec["profile_id"]).execute()
        )

        c_email = get_profile_email(cand["profile_id"])
        c_name = cand_prof.data[0].get("name") if cand_prof.data else "Candidate"

        r_email = get_profile_email(rec["profile_id"])
        r_name = rec_prof.data[0].get("name") if rec_prof.data else "Recruiter"

        # Notify Candidate
        if c_email:
            subject = f"📅 Interview Confirmed: {rec.get('position')} at {rec.get('company')}!"
            body = (
                f"<p>Hi {c_name},</p>"
                f"<p>Congratulations! Your negotiation is complete, and your AI agent has successfully booked an interview for the "
                f"<strong>{rec.get('position')}</strong> role at <strong>{rec.get('company')}</strong>.</p>"
                f"<p><strong>Time:</strong> {meeting_time} (UTC)</p>"
                f"<p><strong>Google Meet Link:</strong> <a href='{meet_link}'>{meet_link}</a></p>"
                f"<p>An invite has also been registered directly in your Google Calendar.</p>"
                f"<p>Best regards,<br/>recruitx Scheduling Agent</p>"
            )
            await send_email_notification(c_email, subject, body)

        # Notify Recruiter
        if r_email:
            subject = f"📅 Interview Scheduled: {c_name} for {rec.get('position')}!"
            body = (
                f"<p>Hi {r_name},</p>"
                f"<p>Good news! Your negotiation loop for the <strong>{rec.get('position')}</strong> role has completed successfully. "
                f"A meeting has been scheduled with <strong>{c_name}</strong>.</p>"
                f"<p><strong>Time:</strong> {meeting_time} (UTC)</p>"
                f"<p><strong>Google Meet Link:</strong> <a href='{meet_link}'>{meet_link}</a></p>"
                f"<p>The slot has been added to your connected Google Calendar.</p>"
                f"<p>Best of luck with the interview!</p>"
                f"<p>Best regards,<br/>recruitx Scheduling Agent</p>"
            )
            await send_email_notification(r_email, subject, body)

    except Exception as e:
        print(f"[notify_meeting_booked error] {str(e)}")
